version: '3.1'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db

  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=contrase単a
    ports:
      - 3307:3306
    volumes:
      - ./db/mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=contrase単a
    ports:
      - 3309:3306
    volumes:
      - ./db/mariadb:/var/lib/mysql

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    environment:
      - MONGODB_HOST=mongodb
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=contrase単a
      - MARIADB_HOST=mariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=contrase単a
    volumes:
      - ./server:/servidor
      - /server/node_modules
